version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: next
  ignore:
  - dependency-name: cypress
    versions:
    - 6.2.0
    - 6.4.0
    - 6.6.0
    - 6.8.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
    - 7.23.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.14
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
    - 2.44.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.12
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: rollup-plugin-filesize
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: rollup-plugin-terser
    versions:
    - 7.0.2
